# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jun  7 18:11:26 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(983, 607)
        MainWindow.setMinimumSize(QtCore.QSize(983, 607))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelblank = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelblank.sizePolicy().hasHeightForWidth())
        self.labelblank.setSizePolicy(sizePolicy)
        self.labelblank.setMinimumSize(QtCore.QSize(20, 99))
        self.labelblank.setMaximumSize(QtCore.QSize(20, 99))
        self.labelblank.setText("")
        self.labelblank.setObjectName("labelblank")
        self.horizontalLayout_4.addWidget(self.labelblank)
        self.MovieEdit = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MovieEdit.sizePolicy().hasHeightForWidth())
        self.MovieEdit.setSizePolicy(sizePolicy)
        self.MovieEdit.setMinimumSize(QtCore.QSize(68, 99))
        self.MovieEdit.setMaximumSize(QtCore.QSize(68, 99))
        self.MovieEdit.setStyleSheet("border-image: url(:/images/Animation Edition2.png);")
        self.MovieEdit.setText("")
        self.MovieEdit.setObjectName("MovieEdit")
        self.horizontalLayout_4.addWidget(self.MovieEdit)
        self.labelarrow = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelarrow.sizePolicy().hasHeightForWidth())
        self.labelarrow.setSizePolicy(sizePolicy)
        self.labelarrow.setMinimumSize(QtCore.QSize(20, 99))
        self.labelarrow.setMaximumSize(QtCore.QSize(20, 99))
        self.labelarrow.setStyleSheet("font: 75 14pt \"SimHei\";\n"
"color: rgb(255, 255, 255);")
        self.labelarrow.setObjectName("labelarrow")
        self.horizontalLayout_4.addWidget(self.labelarrow)
        self.FormatConvert = QtGui.QPushButton(self.groupBox)
        self.FormatConvert.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormatConvert.sizePolicy().hasHeightForWidth())
        self.FormatConvert.setSizePolicy(sizePolicy)
        self.FormatConvert.setMinimumSize(QtCore.QSize(68, 99))
        self.FormatConvert.setMaximumSize(QtCore.QSize(68, 99))
        self.FormatConvert.setStyleSheet("border-image: url(:/images/format conversion2.png);")
        self.FormatConvert.setText("")
        self.FormatConvert.setObjectName("FormatConvert")
        self.horizontalLayout_4.addWidget(self.FormatConvert)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(267, 99))
        self.groupBox_2.setMaximumSize(QtCore.QSize(267, 99))
        self.groupBox_2.setStyleSheet("border:outset;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lebelhello = QtGui.QLabel(self.groupBox_2)
        self.lebelhello.setGeometry(QtCore.QRect(12, 12, 199, 16))
        self.lebelhello.setStyleSheet("font: 75 10pt \"SimHei\";\n"
"color: rgb(214, 214, 214);")
        self.lebelhello.setObjectName("lebelhello")
        self.labelworldcup = QtGui.QLabel(self.groupBox_2)
        self.labelworldcup.setGeometry(QtCore.QRect(6, 29, 77, 67))
        self.labelworldcup.setText("")
        self.labelworldcup.setPixmap(QtGui.QPixmap(":/images/world cup.png"))
        self.labelworldcup.setScaledContents(True)
        self.labelworldcup.setObjectName("labelworldcup")
        self.labelvideoedit = QtGui.QLabel(self.groupBox_2)
        self.labelvideoedit.setGeometry(QtCore.QRect(86, 42, 137, 19))
        self.labelvideoedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 10pt \"SimSun\";")
        self.labelvideoedit.setObjectName("labelvideoedit")
        self.labelvideoconvert = QtGui.QLabel(self.groupBox_2)
        self.labelvideoconvert.setGeometry(QtCore.QRect(86, 68, 137, 16))
        self.labelvideoconvert.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"SimSun\";")
        self.labelvideoconvert.setObjectName("labelvideoconvert")
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 10)
        self.horizontalLayout_4.setStretch(2, 3)
        self.horizontalLayout_4.setStretch(3, 10)
        self.horizontalLayout_4.setStretch(4, 50)
        self.horizontalLayout_4.setStretch(5, 40)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtGui.QGridLayout(self.page)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtGui.QGroupBox(self.page)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtGui.QTabWidget(self.groupBox_3)
        self.tabWidget.setStyleSheet("\n"
" QTabWidget::tab-bar {\n"
"     left: 0px; /* move to the right by 5px */\n"
" }\n"
" QTabBar::tab:selected,QTabBar::tab:!sekected {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 gray, stop: 0.4 gray,\n"
"                                 stop: 0.5 gray, stop: 1.0 gray);\n"
" }\n"
"QTabBar::tab:selected{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
" }\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(249, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(249, 16777215))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_13.setHorizontalSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_6 = QtGui.QWidget(self.groupBox_4)
        self.widget_6.setObjectName("widget_6")
        self.buttonsave = QtGui.QPushButton(self.widget_6)
        self.buttonsave.setGeometry(QtCore.QRect(18, 10, 89, 33))
        self.buttonsave.setStyleSheet("    background-color: rgb(0,150,219);\n"
"    color: rgb(255,255,255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: beige;\n"
"     font: bold 14px;\n"
"")
        self.buttonsave.setObjectName("buttonsave")
        self.buttonpreview = QtGui.QPushButton(self.widget_6)
        self.buttonpreview.setGeometry(QtCore.QRect(126, 10, 91, 33))
        self.buttonpreview.setStyleSheet("    background-color: rgb(0,150,219);\n"
"    color: rgb(255,255,255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: beige;\n"
"     font: bold 14px;\n"
"")
        self.buttonpreview.setObjectName("buttonpreview")
        self.verticalLayout_6.addWidget(self.widget_6)
        self.gridLayout_12.addLayout(self.verticalLayout_6, 2, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.gridLayout_12.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_5 = QtGui.QWidget(self.groupBox_4)
        self.widget_5.setObjectName("widget_5")
        self.buttonloadfile = QtGui.QPushButton(self.widget_5)
        self.buttonloadfile.setGeometry(QtCore.QRect(28, 6, 156, 33))
        self.buttonloadfile.setStyleSheet("background-color: rgb(0,150,219); \n"
"color: rgb(255,255,255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"")
        self.buttonloadfile.setObjectName("buttonloadfile")
        self.labelleadertitle = QtGui.QLabel(self.widget_5)
        self.labelleadertitle.setGeometry(QtCore.QRect(16, 188, 51, 16))
        self.labelleadertitle.setObjectName("labelleadertitle")
        self.labellastrecord = QtGui.QLabel(self.widget_5)
        self.labellastrecord.setGeometry(QtCore.QRect(6, 46, 81, 20))
        self.labellastrecord.setObjectName("labellastrecord")
        self.labelstarttime = QtGui.QLabel(self.widget_5)
        self.labelstarttime.setGeometry(QtCore.QRect(16, 128, 51, 16))
        self.labelstarttime.setObjectName("labelstarttime")
        self.linetimetitle = QtGui.QFrame(self.widget_5)
        self.linetimetitle.setGeometry(QtCore.QRect(6, 172, 241, 16))
        self.linetimetitle.setFrameShape(QtGui.QFrame.HLine)
        self.linetimetitle.setFrameShadow(QtGui.QFrame.Sunken)
        self.linetimetitle.setObjectName("linetimetitle")
        self.labelendtime = QtGui.QLabel(self.widget_5)
        self.labelendtime.setGeometry(QtCore.QRect(16, 154, 51, 16))
        self.labelendtime.setObjectName("labelendtime")
        self.labellastsave = QtGui.QLabel(self.widget_5)
        self.labellastsave.setGeometry(QtCore.QRect(6, 72, 81, 20))
        self.labellastsave.setObjectName("labellastsave")
        self.labellastrecordtime = QtGui.QLabel(self.widget_5)
        self.labellastrecordtime.setGeometry(QtCore.QRect(90, 46, 119, 20))
        self.labellastrecordtime.setObjectName("labellastrecordtime")
        self.labellabellastsavefile = QtGui.QLabel(self.widget_5)
        self.labellabellastsavefile.setGeometry(QtCore.QRect(90, 72, 119, 20))
        self.labellabellastsavefile.setObjectName("labellabellastsavefile")
        self.lineeditstarttime = QtGui.QLineEdit(self.widget_5)
        self.lineeditstarttime.setGeometry(QtCore.QRect(84, 128, 125, 20))
        self.lineeditstarttime.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:outset;")
        self.lineeditstarttime.setObjectName("lineeditstarttime")
        self.lineeditendtime = QtGui.QLineEdit(self.widget_5)
        self.lineeditendtime.setGeometry(QtCore.QRect(84, 156, 125, 20))
        self.lineeditendtime.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:outset;")
        self.lineeditendtime.setObjectName("lineeditendtime")
        self.lineeditleadertitle = QtGui.QLineEdit(self.widget_5)
        self.lineeditleadertitle.setGeometry(QtCore.QRect(84, 186, 125, 20))
        self.lineeditleadertitle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:outset;")
        self.lineeditleadertitle.setObjectName("lineeditleadertitle")
        self.verticalLayout_8.addWidget(self.widget_5)
        self.gridLayout_12.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.gridLayout_12.setRowStretch(0, 80)
        self.gridLayout_12.setRowStretch(1, 10)
        self.gridLayout_12.setRowStretch(2, 15)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_8)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineeditduration = QtGui.QLineEdit(self.groupBox_5)
        self.lineeditduration.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:outset;\n"
"")
        self.lineeditduration.setObjectName("lineeditduration")
        self.horizontalLayout_7.addWidget(self.lineeditduration)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.buttonplayerstop = QtGui.QPushButton(self.groupBox_5)
        self.buttonplayerstop.setStyleSheet("border:outset;")
        self.buttonplayerstop.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonplayerstop.setIcon(icon)
        self.buttonplayerstop.setObjectName("buttonplayerstop")
        self.horizontalLayout_7.addWidget(self.buttonplayerstop)
        self.buttonplayerbackward = QtGui.QPushButton(self.groupBox_5)
        self.buttonplayerbackward.setStyleSheet("border:outset;")
        self.buttonplayerbackward.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonplayerbackward.setIcon(icon1)
        self.buttonplayerbackward.setObjectName("buttonplayerbackward")
        self.horizontalLayout_7.addWidget(self.buttonplayerbackward)
        self.buttonplayerplay = QtGui.QPushButton(self.groupBox_5)
        self.buttonplayerplay.setStyleSheet("border:outset;")
        self.buttonplayerplay.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonplayerplay.setIcon(icon2)
        self.buttonplayerplay.setIconSize(QtCore.QSize(36, 36))
        self.buttonplayerplay.setObjectName("buttonplayerplay")
        self.horizontalLayout_7.addWidget(self.buttonplayerplay)
        self.buttonplayerforward = QtGui.QPushButton(self.groupBox_5)
        self.buttonplayerforward.setStyleSheet("border:outset;")
        self.buttonplayerforward.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonplayerforward.setIcon(icon3)
        self.buttonplayerforward.setObjectName("buttonplayerforward")
        self.horizontalLayout_7.addWidget(self.buttonplayerforward)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.buttonvolume = QtGui.QPushButton(self.groupBox_5)
        self.buttonvolume.setStyleSheet("border:outset;")
        self.buttonvolume.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonvolume.setIcon(icon4)
        self.buttonvolume.setObjectName("buttonvolume")
        self.horizontalLayout_7.addWidget(self.buttonvolume)
        self.slidervolume = QtGui.QSlider(self.groupBox_5)
        self.slidervolume.setMaximumSize(QtCore.QSize(111, 16777215))
        self.slidervolume.setOrientation(QtCore.Qt.Horizontal)
        self.slidervolume.setObjectName("slidervolume")
        self.horizontalLayout_7.addWidget(self.slidervolume)
        self.horizontalLayout_7.setStretch(1, 30)
        self.horizontalLayout_7.setStretch(2, 10)
        self.horizontalLayout_7.setStretch(3, 10)
        self.horizontalLayout_7.setStretch(4, 10)
        self.horizontalLayout_7.setStretch(5, 10)
        self.horizontalLayout_7.setStretch(6, 30)
        self.horizontalLayout_7.setStretch(7, 10)
        self.horizontalLayout_7.setStretch(8, 30)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtGui.QFrame(self.groupBox_5)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sliderseek = QtGui.QSlider(self.groupBox_5)
        self.sliderseek.setStyleSheet("background-color: rgb(rgb(167, 167, 167));")
        self.sliderseek.setOrientation(QtCore.Qt.Horizontal)
        self.sliderseek.setObjectName("sliderseek")
        self.verticalLayout_5.addWidget(self.sliderseek)
        self.gridLayout_10.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.gridLayout_10.setRowStretch(0, 90)
        self.gridLayout_10.setRowStretch(1, 10)
        self.gridLayout_10.setRowStretch(2, 20)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_7)
        self.horizontalLayout_6.setStretch(0, 30)
        self.horizontalLayout_6.setStretch(1, 60)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_8 = QtGui.QWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setMaximumSize(QtCore.QSize(756, 35))
        self.widget_8.setObjectName("widget_8")
        self.buttonstart = QtGui.QPushButton(self.widget_8)
        self.buttonstart.setGeometry(QtCore.QRect(10, 0, 109, 35))
        self.buttonstart.setStyleSheet("background-color: rgb(0,150,219); \n"
"color: rgb(255,255,255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"")
        self.buttonstart.setObjectName("buttonstart")
        self.buttoncancel = QtGui.QPushButton(self.widget_8)
        self.buttoncancel.setGeometry(QtCore.QRect(148, 0, 109, 35))
        self.buttoncancel.setStyleSheet("background-color: rgb(0,150,219); \n"
"color: rgb(255,255,255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"")
        self.buttoncancel.setObjectName("buttoncancel")
        self.buttonexamine = QtGui.QPushButton(self.widget_8)
        self.buttonexamine.setGeometry(QtCore.QRect(290, 0, 109, 35))
        self.buttonexamine.setStyleSheet("background-color: rgb(0,150,219); \n"
"color: rgb(255,255,255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: bold 14px;\n"
"")
        self.buttonexamine.setObjectName("buttonexamine")
        self.horizontalLayout_8.addWidget(self.widget_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout_14.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_7 = QtGui.QWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMaximumSize(QtCore.QSize(758, 63))
        self.widget_7.setObjectName("widget_7")
        self.labelfilename = QtGui.QLabel(self.widget_7)
        self.labelfilename.setGeometry(QtCore.QRect(104, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setPointSize(9)
        self.labelfilename.setFont(font)
        self.labelfilename.setObjectName("labelfilename")
        self.labeloutputset = QtGui.QLabel(self.widget_7)
        self.labeloutputset.setGeometry(QtCore.QRect(2, 2, 91, 21))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(15)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.labeloutputset.setFont(font)
        self.labeloutputset.setStyleSheet("font: 15pt \"SimHei\";")
        self.labeloutputset.setObjectName("labeloutputset")
        self.labelsaveto = QtGui.QLabel(self.widget_7)
        self.labelsaveto.setGeometry(QtCore.QRect(104, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setPointSize(9)
        self.labelsaveto.setFont(font)
        self.labelsaveto.setObjectName("labelsaveto")
        self.buttonbrowse = QtGui.QPushButton(self.widget_7)
        self.buttonbrowse.setGeometry(QtCore.QRect(672, 38, 75, 23))
        self.buttonbrowse.setObjectName("buttonbrowse")
        self.labelfilenameblank = QtGui.QLabel(self.widget_7)
        self.labelfilenameblank.setGeometry(QtCore.QRect(164, 10, 487, 23))
        self.labelfilenameblank.setStyleSheet("background-color: white;")
        self.labelfilenameblank.setText("")
        self.labelfilenameblank.setObjectName("labelfilenameblank")
        self.labelsaveblank = QtGui.QLabel(self.widget_7)
        self.labelsaveblank.setGeometry(QtCore.QRect(164, 38, 487, 23))
        self.labelsaveblank.setStyleSheet("background-color: white;")
        self.labelsaveblank.setText("")
        self.labelsaveblank.setObjectName("labelsaveblank")
        self.verticalLayout_10.addWidget(self.widget_7)
        self.gridLayout_14.addLayout(self.verticalLayout_10, 1, 0, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_2.setStyleSheet("background-color:white;")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_12.addWidget(self.tableWidget_2)
        self.labelmerge = QtGui.QLabel(self.tab_2)
        self.labelmerge.setStyleSheet("background-color:white;")
        self.labelmerge.setObjectName("labelmerge")
        self.verticalLayout_12.addWidget(self.labelmerge)
        self.gridLayout_14.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.gridLayout_14.setRowStretch(0, 50)
        self.gridLayout_14.setRowStretch(1, 25)
        self.gridLayout_14.setRowStretch(2, 15)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_17 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_2 = QtGui.QWidget(self.page_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.buttontransnew = QtGui.QPushButton(self.widget_2)
        self.buttontransnew.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.buttontransnew.setObjectName("buttontransnew")
        self.horizontalLayout_9.addWidget(self.buttontransnew)
        self.buttontransbegin = QtGui.QPushButton(self.widget_2)
        self.buttontransbegin.setStyleSheet("background-color: rgb(222, 222, 222);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/begin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttontransbegin.setIcon(icon5)
        self.buttontransbegin.setObjectName("buttontransbegin")
        self.horizontalLayout_9.addWidget(self.buttontransbegin)
        self.buttontranspause = QtGui.QPushButton(self.widget_2)
        self.buttontranspause.setStyleSheet("background-color: rgb(222, 222, 222);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttontranspause.setIcon(icon6)
        self.buttontranspause.setObjectName("buttontranspause")
        self.horizontalLayout_9.addWidget(self.buttontranspause)
        self.buttontransdelete = QtGui.QPushButton(self.widget_2)
        self.buttontransdelete.setStyleSheet("background-color: rgb(222, 222, 222);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttontransdelete.setIcon(icon7)
        self.buttontransdelete.setObjectName("buttontransdelete")
        self.horizontalLayout_9.addWidget(self.buttontransdelete)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.gridLayout_16.addWidget(self.widget_2, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 1, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.labelallmission = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelallmission.sizePolicy().hasHeightForWidth())
        self.labelallmission.setSizePolicy(sizePolicy)
        self.labelallmission.setMaximumSize(QtCore.QSize(133, 50))
        self.labelallmission.setStyleSheet("background-color: rgb(167, 167, 167); \n"
"font: 15pt \"SimHei\";")
        self.labelallmission.setObjectName("labelallmission")
        self.gridLayout_20.addWidget(self.labelallmission, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.listWidget = QtGui.QListWidget(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(133, 16777215))
        self.listWidget.setStyleSheet("background-color: rgbrgb(167, 167, 167);")
        self.listWidget.setObjectName("listWidget")
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        self.gridLayout_21.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_21, 1, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.tabletrans = QtGui.QTableWidget(self.page_2)
        self.tabletrans.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.tabletrans.setObjectName("tabletrans")
        self.tabletrans.setColumnCount(4)
        self.tabletrans.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabletrans.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabletrans.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabletrans.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabletrans.setHorizontalHeaderItem(3, item)
        self.tabletrans.horizontalHeader().setDefaultSectionSize(200)
        self.tabletrans.horizontalHeader().setHighlightSections(False)
        self.tabletrans.horizontalHeader().setMinimumSectionSize(2500)
        self.gridLayout_18.addWidget(self.tabletrans, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_18, 1, 1, 1, 1)
        self.gridLayout_17.setColumnStretch(0, 10)
        self.gridLayout_17.setColumnStretch(1, 60)
        self.gridLayout_17.setRowStretch(0, 10)
        self.gridLayout_17.setRowStretch(1, 70)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelversions = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelversions.sizePolicy().hasHeightForWidth())
        self.labelversions.setSizePolicy(sizePolicy)
        self.labelversions.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelversions.setObjectName("labelversions")
        self.horizontalLayout.addWidget(self.labelversions)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.labelchinamoblie = QtGui.QLabel(self.centralWidget)
        self.labelchinamoblie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelchinamoblie.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelchinamoblie.setObjectName("labelchinamoblie")
        self.horizontalLayout.addWidget(self.labelchinamoblie)
        self.horizontalLayout.setStretch(0, 30)
        self.horizontalLayout.setStretch(1, 50)
        self.horizontalLayout.setStretch(2, 30)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 20)
        self.verticalLayout.setStretch(1, 89)
        self.verticalLayout.setStretch(2, 3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.labelarrow.setText(QtGui.QApplication.translate("MainWindow", " >", None, QtGui.QApplication.UnicodeUTF8))
        self.lebelhello.setText(QtGui.QApplication.translate("MainWindow", "您好，融创天下股份有限公司", None, QtGui.QApplication.UnicodeUTF8))
        self.labelvideoedit.setText(QtGui.QApplication.translate("MainWindow", "视频编辑：共计203集", None, QtGui.QApplication.UnicodeUTF8))
        self.labelvideoconvert.setText(QtGui.QApplication.translate("MainWindow", "视频转码：共计203集", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonsave.setText(QtGui.QApplication.translate("MainWindow", "保存", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonpreview.setText(QtGui.QApplication.translate("MainWindow", "预览", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonloadfile.setText(QtGui.QApplication.translate("MainWindow", "导入视频文件", None, QtGui.QApplication.UnicodeUTF8))
        self.labelleadertitle.setText(QtGui.QApplication.translate("MainWindow", "片头标题", None, QtGui.QApplication.UnicodeUTF8))
        self.labellastrecord.setText(QtGui.QApplication.translate("MainWindow", "上次截取记录：", None, QtGui.QApplication.UnicodeUTF8))
        self.labelstarttime.setText(QtGui.QApplication.translate("MainWindow", "起始时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.labelendtime.setText(QtGui.QApplication.translate("MainWindow", "结束时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.labellastsave.setText(QtGui.QApplication.translate("MainWindow", "上次保存文件：", None, QtGui.QApplication.UnicodeUTF8))
        self.labellastrecordtime.setText(QtGui.QApplication.translate("MainWindow", "00:00:00—00:05:31", None, QtGui.QApplication.UnicodeUTF8))
        self.labellabellastsavefile.setText(QtGui.QApplication.translate("MainWindow", "秦时明月", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "视频截取", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonstart.setText(QtGui.QApplication.translate("MainWindow", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.buttoncancel.setText(QtGui.QApplication.translate("MainWindow", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonexamine.setText(QtGui.QApplication.translate("MainWindow", "查看", None, QtGui.QApplication.UnicodeUTF8))
        self.labelfilename.setText(QtGui.QApplication.translate("MainWindow", "文件名：", None, QtGui.QApplication.UnicodeUTF8))
        self.labeloutputset.setText(QtGui.QApplication.translate("MainWindow", "输出设置", None, QtGui.QApplication.UnicodeUTF8))
        self.labelsaveto.setText(QtGui.QApplication.translate("MainWindow", "保存到：", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonbrowse.setText(QtGui.QApplication.translate("MainWindow", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "文件名称", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "时长", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "分辨率", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "状态", None, QtGui.QApplication.UnicodeUTF8))
        self.labelmerge.setText(QtGui.QApplication.translate("MainWindow", "共有3个视频准备合并", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "视频合并", None, QtGui.QApplication.UnicodeUTF8))
        self.buttontransnew.setText(QtGui.QApplication.translate("MainWindow", "新建任务", None, QtGui.QApplication.UnicodeUTF8))
        self.buttontransbegin.setText(QtGui.QApplication.translate("MainWindow", "开始", None, QtGui.QApplication.UnicodeUTF8))
        self.buttontranspause.setText(QtGui.QApplication.translate("MainWindow", "暂停", None, QtGui.QApplication.UnicodeUTF8))
        self.buttontransdelete.setText(QtGui.QApplication.translate("MainWindow", "删除", None, QtGui.QApplication.UnicodeUTF8))
        self.labelallmission.setText(QtGui.QApplication.translate("MainWindow", "   全部任务", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(1).setText(QtGui.QApplication.translate("MainWindow", "进行中", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(3).setText(QtGui.QApplication.translate("MainWindow", "已完成", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabletrans.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "动画名称", None, QtGui.QApplication.UnicodeUTF8))
        self.tabletrans.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "转码进度", None, QtGui.QApplication.UnicodeUTF8))
        self.tabletrans.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "状态", None, QtGui.QApplication.UnicodeUTF8))
        self.tabletrans.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "输出路径", None, QtGui.QApplication.UnicodeUTF8))
        self.labelversions.setText(QtGui.QApplication.translate("MainWindow", "当前版本 V1.0 Beta", None, QtGui.QApplication.UnicodeUTF8))
        self.labelchinamoblie.setText(QtGui.QApplication.translate("MainWindow", "中国移动手机动漫基地", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
